### PR TITLE
Added from_str_sep to handle separator/delimiter

### PR DESCRIPTION
**Pull request by ianxek**
I also added the corresponding tests and doc examples with tests.

This allows users of your library to benefit from the nice interface you provide also in the case of a non-default delimiter.

I ran the tests with cargo test.

### CODE REVIEW

**Comment by imbolc** [comment]
Thanks, I'm ok with adding the shortcut, a few issues though:
1. I'd like to keep the usage example as simple as possible. Exactly as it was actually, sorry :) I don't actually understand where one would need that `Bar` newtype example. Maybe you move the example to the `from_str_sep` doc comment?
2. Shouldn't we be consistent with `delimiter` / `separator`. Maybe `from_str_delim`? Or we can replace `delimiter` with `separator` everywhere.

**Comment by ianxek** [comment]
1. Yes, I'll move it.
2. It is better to change delimiter to separator I think, if only because of the meaning of the CSV acronym.

I'll do that in two commits.

**Comment by imbolc** [comment]
Thank you :+1:

**Comment by ianxek** [comment]
My pleasure! Thanks for accepting my PR.

**Pull request merged**
